CTMS - O6U/Controllers/TransportedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CTMS___O6U.Models;
using System.Net.Http;
using System.Text.RegularExpressions;
using Microsoft.Reporting.WebForms;
using System.IO;

namespace CTMS___O6U.Controllers
{
    public class TransportedController : Controller
    {
        // GET: Transported
        public ActionResult Index()
        {
            try
            {
                ViewBag.RequestResult = TempData["RequestResult"].ToString();
            }
            catch (Exception) { }

            List<TransportedMatrialModel> training = new List<TransportedMatrialModel>();

            HttpResponseMessage res = ApiCall.getFromApi("api/TransportedMatriels");
            TransportedMatrialModel[] dtt = null;
            if (res != null)
            {
                var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<TransportedMatrialModel[]>(d);
            }
            return View(dtt.Where(e => e.Archive == false));
            //return View();
        }

        [HttpPost]
        public ActionResult Index(string statue)
        {

            TempData["RequestResult"] = statue;
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        { 
            HttpResponseMessage transportedgData = ApiCall.getFromApi("api/TransportedMatriels/" + id);
            if (transportedgData == null)
                return HttpNotFound();

            List<TransportedMatrialModel> data = new List<TransportedMatrialModel>();
            data.Add(transportedgData.Content.ReadAsAsync<TransportedMatrialModel>().Result);
            TransportedMatrialModel tdata = data[0];
            return View(tdata);
        }

        public ActionResult Save(int id, TransportedMatrialModel transported)
        {
            int res = ApiCall.getFromApi("api/TransportedMatriels/" + id, transported);
            switch (res)
            {
                case 201:
                    return Index("Record Saved Successfully");
                default:
                    break;
            }
            return Index("Something went worng");
        }

        public ActionResult Create()
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/DummyMaterials");
            DummyMaterialModel[] dtt = null;
            if (res != null)
            {
                var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<DummyMaterialModel[]>(d);
            }

            ViewBag.materials = new SelectList(dtt, "matrial_id", "name");

            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "id,source,destination,material_id,quantity")] TransportedMatrialModel transported)
        {
            DateTime curr = DateTime.Now;
            transported.time_stamp = Convert.ToDateTime(curr.ToString("yyyy-MM-dd HH:mm:ss.fff"));
            int res = ApiCall.getFromApi("api/TransportedMatriels", transported);
            switch (res)
            {
                case 201:
                    return Index("Record Added Successfully");
                default:
                    break;
            }
            return Index("Something went worng");
        }

        public ActionResult Details(int id)
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/TransportedMatriels/" + id);
            TransportedMatrialModel transportedMaterials = new TransportedMatrialModel();
            if (res != null)
            {
                transportedMaterials = res.Content.ReadAsAsync<TransportedMatrialModel>().Result;
            }

            return View(transportedMaterials);
        }

        public ActionResult Delete(int id)
        {

            int res = ApiCall.deleteFromApi("api/TransportedMatriels/" + id);
            switch (res)
            {
                case 200:
                    return Index("Record Deleted!");
                default:
                    break;
            }

            return Index("Something went worng");
        }

        [HttpGet]
        public ActionResult Assign(int id)
        {
            HttpResponseMessage matres = ApiCall.getFromApi("api/TransportedMatriels/"+id);
            TransportedMatrialModel tranMat = null;
            if(matres != null)
            {
                var d = matres.Content.ReadAsStringAsync().Result;
                tranMat = Newtonsoft.Json.JsonConvert.DeserializeObject<TransportedMatrialModel>(d);
            }



            HttpResponseMessage res = ApiCall.getFromApi("api/ComapnyMaterials");
            CompanyMaterialModel[] dtt = null;
            if (res != null)
            {
                var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<CompanyMaterialModel[]>(d);
            }

            ViewBag.CompanyNames = new SelectList(dtt.Where(e => e.Archive == false)
                .Where(e => e.matrial_id == tranMat.material_id).Select(e => e.company), "id","name");

            ViewBag.id = id;

            ViewBag.quantity = tranMat.Quantity;
            return View();
        }

        [HttpPost]
        public ActionResult Assign(string dataName)
        {
            try
            {
                string cleanedData = Regex.Replace(dataName, @"[^0-9a-zA-Z,]", "");
                string[] dataVal = cleanedData.Split(',');
                int[] myInts = Array.ConvertAll(dataVal, s => int.Parse(s));
                for (int i = 0; i < myInts.Length; i++)
                {
                    CarTransportedDriverModel addData = new CarTransportedDriverModel();
                    addData.car_id = myInts[i];
                    addData.transported_id = Convert.ToInt32(RouteData.Values["id"]);
                    addData.driver_id = myInts[++i];

                    int res = ApiCall.getFromApi("api/CarTransportDriver", addData);

                }
                return Index("Driver Assigned");
            }
            catch(HttpException e)
            {
                return Index("Something went worng");
            }
            
        }

        public JsonResult getDrivers(int companyId)
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/drivers/bycompany/"+companyId);
            DriverModel[] dtt = null;
            if (res != null)
            {
                var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<DriverModel[]>(d);
            }

            return Json(dtt.Where(e => e.Archive == false), JsonRequestBehavior.AllowGet);
        }

        public JsonResult getCars(int companyId)
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/cars/bycompany/"+companyId);
            CarModel[] dtt = null;
            if (res != null)
            {
                var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<CarModel[]>(d);
            }

            return Json(dtt.Where(e => e.Archive == false && e.satisfied == true), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Unassign(int id)
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/CarTransportDriver");
            CarTransportedDriverModel[] dtt = null;
            if (res != null)
            {
                var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<CarTransportedDriverModel[]>(d);
            }


            ViewBag.id = id;
            return View(dtt.Where(e => e.Archive == false));
        }

        [HttpPost]
        public ActionResult Unassign(string dataName)
        {
            try
            {
                string cleanedData = Regex.Replace(dataName, @"[^0-9a-zA-Z,]", "");
                string[] dataVal = cleanedData.Split(',');
                int[] myInts = Array.ConvertAll(dataVal, s => int.Parse(s));
                for (int i = 0; i < dataVal.Length; i++)
                {
                    int id = myInts[i];

                    int res = ApiCall.deleteFromApi("api/CarTransportDriver/" + id);
                    switch (res)
                    {
                        case 200:
                            return Index("Record Deleted!");
                        default:
                            break;
                    }

                    return Index("Something went worng");

                }
                return Index("Driver Assigned");
            }
            catch (HttpException e)
            {
                return Index("Something went worng");
            }

        }

        public ActionResult Report(DateTime? startDate, DateTime? endDate/*,int? company_id*/)
        {

            List<TransportedMatrialModel> company = new List<TransportedMatrialModel>();
            HttpResponseMessage res = ApiCall.getFromApi("api/TransportedMatriels");

            if (res != null)
            {
                company = res.Content.ReadAsAsync<List<TransportedMatrialModel>>().Result;
                var ret = company.Where(e => e.Archive == false);

                if (startDate != null && endDate != null)
                {
                    ret = ret.Where(e => e.time_stamp.Date >= startDate.Value.Date && e.time_stamp.Date <= endDate.Value.Date);
                }
                //if (company_id != null)
                //    ret.Where(e => e.car_transport_driver.Where(c=> c.car.company_id == company_id));
                return View(ret);
            }

            return View();
        }

        //public ActionResult Report(string ReportType)
        //{
        //    LocalReport lr = new LocalReport();

CTMS - O6U/Views/Transported/Assign.cshtml
@model CTMS___O6U.Models.CarTransportedDriverModel

@{
    ViewBag.Title = "Assign";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<h2>Assign Drivers to shipment</h2>

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">

        <div class="row">

            <div class="col-xs-6 col-*-offset-3" style="margin-bottom:20px;">
                @Html.Label("Company", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownList("Company", ViewBag.CompanyNames as SelectList, "-- Select Status --",
               new { @class = "form-control", @id = "companyLt" })
            </div>
        </div>

        <div class="row">
            <div class="col-xs-6">
                @Html.Label("Driver", htmlAttributes: new { @class = "control-label col-md-2" })
                <select id="driverslt" class="form-control" name="Driver">
                    <option value=""></option>
                </select>
            </div>

            <div class="col-xs-6">
                @Html.Label("Car", htmlAttributes: new { @class = "control-label col-md-2" })
                <select id="carslt" class="form-control" name="Car">
                    <option value=""></option>
                </select>
            </div>
        </div>
        @Html.ValidationMessageFor(model => model.driver_id, "", new { @class = "text-danger" })

    </div>

    <div class="form-group">
        <div class="col-md-offset-4 col-md-4" style="margin-bottom:30px;margin-top:20px;">
            <input type="button" onclick="newElement()" value="Add to list" class="btn btn-default addBtn" style="width:100%;" />
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">
            <table id="datalist" class="table">
                <thead>
                    <tr>
                        <th>Driver name</th>
                        <th>Car plate number</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody id="datalistBody"></tbody>
            </table>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="dataName" id="stringIn" />
        <div class="form-group">
            <div class="col-md-offset-4 col-md-4" style="margin-bottom:30px;margin-top:20px;">
                <input id="assiBtn" type="submit" value="Assign" class="btn btn-default" style="width:100%;"/>
            </div>
        </div>

     } 
</div>

<script>
    var carQuanArray = {};
    $(function () {
        $("#companyLt").change(function () {

            $.get("/Transported/getDrivers", { companyId: $("#companyLt").val() }, function (data) {
                $("#driverslt").empty();
                $.each(data, function (index, row) {
                    $("#driverslt").append("<option value='" + row.id + "'>" + row.name + "</option>")
                });
            });

            $.get("/Transported/getCars", { companyId: $("#companyLt").val() }, function (data) {
                $("#carslt").empty();
                $.each(data, function (index, row) {
                    $("#carslt").append("<option value='" + row.id + "'>" + row.plate_number + " - " + row.model + "</option>")
                    carQuanArray['id' + row.id] = row.Capcity;
                });
            });
        });
    });

    var assignVal = new Array();
    var quantity = '@ViewBag.quantity';

    $('form').submit(function (e) {
        assignVal = [];
        var quan = 0;
        $("#datalist").find("tr").find("td[class='carId']").each(function (index) {
            assignVal[assignVal.length] = $(this).text();
            quan += carQuanArray['id' + $(this).text()];
            assignVal[assignVal.length] = $(this).closest("tr").find("td[class='driverId']").text();
        });
        if (quan < quantity) {
            alert("The shippment quantity is " + quantity + " while assigned cars can only carry " + quan);
            alert('submit intercepted');
            e.preventDefault(e);
        } else {
            alert("done");
            $('#stringIn').val(assignVal.toString());
        }

    });

    

    //$("#assiBtn").click(function () {
    //    assignVal = [];
    //    var quan = 0;
    //    $("#datalist").find("tr").find("td[class='carId']").each(function (index) {
    //        assignVal[assignVal.length] = $(this).text();
    //        quan += carQuanArray['id' + $(this).text()]; 
    //        assignVal[assignVal.length] = $(this).closest("tr").find("td[class='driverId']").text();
    //    });
    //    if (quan < quantity) {

    //    }
    //    $('#stringIn').val(assignVal.toString());
    //});

    var close = document.getElementsByClassName("close");
    var i;


    for (i = 0; i < close.length; i++) {
        close[i].onclick = function () {
            $(this).closest('tr').remove();

            var div = this.parentElement;
            div.style.display = "none";
        }
    }

    function newElement() {

        var dradded = false;
        var caradded = false;
       

        var drivlt = document.getElementById("driverslt");
        var carlt = document.getElementById("carslt");

        var table = document.getElementById("datalistBody");

        var tr = document.createElement("tr");
        var td1, td2, td3, td4;
        td1 = document.createElement("td");
        td2 = document.createElement("td");
        td3 = document.createElement("td");
        td4 = document.createElement("td");

        var data1 = document.createTextNode(drivlt.options[drivlt.selectedIndex].value);
        var data2 = document.createTextNode(drivlt.options[drivlt.selectedIndex].text);
        var data3 = document.createTextNode(carlt.options[carlt.selectedIndex].value);
        var data4 = document.createTextNode(carlt.options[carlt.selectedIndex].text);

        var d = document.getElementsByClassName("driverId");
        var c = document.getElementsByClassName("carId");

        for (var x = 0; x < d.length; x++) {
            if (d[x].textContent == drivlt.options[drivlt.selectedIndex].value)
            {
                dradded = true;
                break;
            }
        }

        if (!dradded) {
            for (var x = 0; x < c.length; x++) {
                if (c[x].textContent == carlt.options[carlt.selectedIndex].value) {
                    caradded = true;
                    break;
                }
            }
        }

        if (companyLt.options[companyLt.selectedIndex].value == "") {
            alert("you must select a company");
        } else if (drivlt.options[drivlt.selectedIndex].value == "") {
            alert("Please select a driver");
        } else if (carlt.options[carlt.selectedIndex].value == "") {
            alert("Please select a car");
        } else if (dradded || caradded) {
            if (dradded)
                alert("Driver already added ! ");
            else
                alert("Car alreadt added !");
        }
        else {
            td1.appendChild(data1);
            tr.appendChild(td1);
            td1.className = "driverId";
            td1.style.display = "none";
            td2.appendChild(data2);
            tr.appendChild(td2);
            td3.appendChild(data3);
            tr.appendChild(td3);
            td3.className = "carId";
            td3.style.display = "none";
            td4.appendChild(data4);
            tr.appendChild(td4);
            
            var span = document.createElement("SPAN");
            var txt = document.createTextNode("\u00D7");
            span.className = "close";
            span.appendChild(txt);
            tr.appendChild(span);


            table.appendChild(tr);

            for (i = 0; i < close.length; i++) {
                close[i].onclick = function () {
                    $(this).closest('tr').remove();
                    var div = this.parentElement;
                    div.style.display = "none";
                }
            }
        }
    }

</script>

CTMS - O6U/Views/Transported/Create.cshtml
@model CTMS___O6U.Models.TransportedMatrialModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TransportedMatrialModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.source, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.source, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.source, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.material_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.material_id ,ViewBag.materials as SelectList, "-- Select Material --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.material_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CTMS - O6U/Views/Transported/Details.cshtml
@model CTMS___O6U.Models.TransportedMatrialModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TransportedMatrialModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.source)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.source)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time_stamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time_stamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.material_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.material_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CTMS - O6U/Views/Transported/Report.cshtml
@model IEnumerable<CTMS___O6U.Models.TransportedMatrialModel>

@{
    ViewBag.Title = "Report";
}

<h2>Report</h2>

@*@Html.ActionLink("Export To PDF", "Report", new { ReportType = "PDF" })  |
@Html.ActionLink("Export To Word", "Report", new { ReportType = "Word" })  |
@Html.ActionLink("Export To Excel", "Report", new { ReportType = "Excel" })  |
@Html.ActionLink("Export To Image", "Report", new { ReportType = "Image" })*@

@using (Html.BeginForm("Report", "Transported", FormMethod.Get))
{
    <div>
        <form>
            From:
            <input type="date" name="startDate" , id="txtFromDate">
            to:
            <input type="date" name="endDate" , id="txtToDate">
        </form>

        <input type="submit" value="Filter" />
    </div>
    <br />
    <button id="download_pdf">generate PDF</button>

}
<br />
<div id="content">
    @foreach (var item in Model)
    {
        <div>
            <dl>
                <dt>
                    @Html.DisplayNameFor(model => model.source)
                </dt>

                <dd>
                    <text>&nbsp;</text>
                    @Html.DisplayFor(model => item.source)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.destination)
                </dt>

                <dd>
                    <text>&nbsp;</text>
                    @Html.DisplayFor(model => item.destination)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.time_stamp)
                </dt>

                <dd>
                    <text>&nbsp;</text>
                    @Html.DisplayFor(model => item.time_stamp)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Quantity)
                </dt>

                <dd>
                    <text>&nbsp;</text>
                    @Html.DisplayFor(model => item.Quantity)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.material_id)
                </dt>

                <dd>
                    <text>&nbsp;</text>
                    @Html.DisplayFor(model => item.material_id)
                </dd>

            </dl>
        </div>
        <br />
        <div>
            <table class="table">
                @*<thead>*@
                <tr>
                    <th>
                        @Html.DisplayName("Comapnay Name")
                    </th>
                    <th>
                        @Html.DisplayName("Car Id")
                    </th>
                    <th>
                        @Html.DisplayName("Driver Id")
                    </th>

                </tr>
                @*</thead>*@

                @*<tbody>*@
                @foreach (var it in item.car_transport_driver.Where(e => e.Archive == false))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => it.driver.company.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => it.car_id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => it.driver_id)
                        </td>

                    </tr>
                }
                @*</tbody>*@
            </table>
        </div>
        <hr />

    }
</div>

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.debug.js" integrity="sha384-CchuzHs077vGtfhGYl9Qtc7Vx64rXBXdIAZIPbItbNyWIRTdG0oYAqki3Ry13Yzu" crossorigin="anonymous"></script>
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")

    <script>
        $(document).ready(function () {

            //$('#download_pdf').click(function () {
            //    html2canvas(document.body, {
            //        onrendered: function (canvas) {
            //            var img = canvas.toDataURL("image/png");
            //            var doc = new jsPDF();
            //            doc.addImage(img, 'JPEG', 5,5);
            //            doc.save('test.pdf');
            //        }
            //    });
            //});
            //var doc = new jsPDF();
            //var specialElementHandlers = {
            //    '#editor': function (element, renderer) {
            //        return true;
            //    }
            //};

            //$('#download_pdf').click(function () {
            //    doc.fromHTML($('#content').html(), 15, 15, {
            //        'width': 170,
            //        'elementHandlers': specialElementHandlers
            //    });
            //    doc.save('sample-file.pdf');
            //});

            $('#download_pdf').click(function () {
                var pdf = new jsPDF('p', 'pt', 'A4')
                    , source = $('#content')[0]
                    , specialElementHandlers = {
                        '#bypassme': function (element, renderer) {
                            return true
                        }
                    }

                margins = { top: 60, bottom: 60, left: 40, width: 80 };
                pdf.fromHTML(source, margins.left, margins.top, {
                    'width': margins.width,
                    'elementHandlers': specialElementHandlers
                },
                    function (dispose) {
                        pdf.save('download_pdf.pdf');
                    }, margins
                )
            });
        });

    </script>
}
@*<script>
        $(document).ready(function () {
            $("#txtFromDate").datepicker({
                numberOfMonths: 2,
                onSelect: function (selected) {
                    $("#txtToDate").datepicker("option", "minDate", selected)
                }
            });
            $("#txtToDate").datepicker({
                numberOfMonths: 2,
                onSelect: function (selected) {
                    $("#txtFromDate").datepicker("option", "maxDate", selected)
                }
            });
        });
    </script>*@

CTMS - O6U/Views/Transported/edit.cshtml
@model CTMS___O6U.Models.TransportedMatrialModel

@{
    ViewBag.Title = "edit";
}

<h2>edit</h2>


@using (Html.BeginForm("Save", "Transported"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TransportedMatrialModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.source, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.source, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.source, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time_stamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time_stamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time_stamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}