CTMS - O6U/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CTMS___O6U.Models;
using System.Net.Http;
using System.Web.UI;

namespace CTMS___O6U.Controllers
{
    public class DriverController : Controller
    {
        // GET: Driver
        public ActionResult Index()
        {
            try
            {
                ViewBag.RequestResult = TempData["RequestResult"].ToString();
            }
            catch (Exception) { }

            List<DriverModel> driver = new List<DriverModel>();

            HttpResponseMessage res = ApiCall.getFromApi("api/drivers");
            DriverModel [] dtt = null;
            if (res != null)
            {
               var d = res.Content.ReadAsStringAsync().Result;
                dtt = Newtonsoft.Json.JsonConvert.DeserializeObject<DriverModel []>(d);
                var q = dtt.Where(e => e.Archive == false);
                return View(q);
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(string statue)
        {
            TempData["RequestResult"] = statue;
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Include = "id,ssn,phone,name,address,birth_date,license_degree,companys_id")] DriverModel driver)
        {
            driver.Archive = false;
            int res = ApiCall.getFromApi("api/drivers/", driver);
            switch (res)
            {
                case 201:
                    return Index("Record Added Successfully");
                default:
                    break;
            }
            return Index("Something went worng");
        }

        public ActionResult Delete(int id)
        {

            int res = ApiCall.deleteFromApi("api/drivers/" + id);
            switch (res)
            {
                case 200:
                    return Index("Record Deleted!");
                default:
                    break;
            }

            return Index("Something went worng");
        }

        public ActionResult Edit(int id)
        {
            HttpResponseMessage driverdata = ApiCall.getFromApi("api/drivers/" + id);
            if (driverdata == null)
                return HttpNotFound();

            List<DriverModel> drivers = new List<DriverModel>();
            drivers.Add(driverdata.Content.ReadAsAsync<DriverModel>().Result);
            DriverModel driver = drivers[0];
            return View(driver);
        }

        public ActionResult Save(int id, DriverModel driver)
        {
            int res = ApiCall.getFromApi("api/drivers/" + id, driver);
            switch (res)
            {
                case 201:
                    return Index("Record Saved Successfully");
                default:
                    break;
            }
            return Index("Something went worng");
        }


        public ActionResult Details(int id)
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/Drivers/" + id);
            DriverModel driver = new DriverModel();
            if (res != null)
            {
                driver = res.Content.ReadAsAsync<DriverModel>().Result;
            }

            return View(driver);
        }


    }
}

CTMS - O6U/Views/Driver/Create.cshtml
@model CTMS___O6U.Models.DriverModel

@{
    ViewBag.Title = "Create";
}

<h2>Add New Driver</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>DriverModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ssn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ssn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ssn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birth_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birth_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birth_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.license_degree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.license_degree, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.license_degree, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companys_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("companys_id",
                    new SelectList(Enumerable.Empty<SelectListItem>(), "id", "name"),
                    "-- Select a Company --",
                    new { @class = "form-control" })
                @*@Html.EditorFor(model => model.companys_id, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.companys_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $.ajax({
                url: WebApiURL.Url()  + "companies",
                contentType: "application/json; charset=utf-8",
                type: "GET",
                data:"",
                dataType:"JSON",
                success: function (result) {
                    $.each(result, function (key, value) {
                        if (value.archive == false)
                            $("#companys_id").append($("<option> </option>").val(value.id).html(value.id + ' ' + value.name));
                    });
                },
                error: function (data) { }
            });
        });
</script>

}

CTMS - O6U/Views/Driver/Details.cshtml
@model CTMS___O6U.Models.DriverModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    @*<h4>DriverModel</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ssn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ssn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.birth_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birth_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.license_degree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.license_degree)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.companys_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.companys_id)
        </dd>

    </dl>
</div>

<hr />
<table class="table">
    <thead>
        <tr>
            <th>Training Name</th>
            <th>Duration</th>
            <th>Starting Date</th>
            <th>Notes</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Drivers_Training.Where(e=>e.Archive == false))
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Training.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Training.Duration)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.StartingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>

        </tr>
        }
    </tbody>
</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CTMS - O6U/Views/Driver/Edit.cshtml
@model CTMS___O6U.Models.DriverModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Driver</h2>


@using (Html.BeginForm("Save", "Driver"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>DriverModel</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.ssn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ssn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ssn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birth_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birth_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birth_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.license_degree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.license_degree, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.license_degree, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.companys_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.companys_id, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("companys_id",
                 new SelectList(Enumerable.Empty<SelectListItem>(), "id", "name"),
                 "-- Select a Company --",
                 new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.companys_id, "", new { @class = "text-danger" })
                @Html.ValidationMessageFor(model => model.companys_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
    $(document).ready(function () {
        $.ajax({
            url: WebApiURL.Url()  + "companies",
            contentType: "application/json; charset=utf-8",
            type: "GET",
            data:"",
            dataType:"JSON",
            success: function (result) {
                $.each(result, function (key, value) {
                    if (value.archive == false)
                        $("#companys_id").append($("<option> </option>").val(value.id).html(value.id + ' ' + value.name));
                });
                $("#companys_id").val(@Model.companys_id)
            },
            error: function (data) { }
        });
    });
    </script>

}

CTMS - O6U/Views/Driver/Index.cshtml
@model IEnumerable<CTMS___O6U.Models.DriverModel>

@{
    ViewBag.Title = "Index";
}


@if (ViewBag.RequestResult != null)
{
    <div class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Info:</span>
        @ViewBag.RequestResult
    </div>
}

<h2>Drivers Information</h2>

<p>
    @Html.ActionLink("Create New", "Create","Driver",null,new {@class="btn btn-primary" })
</p>
<table id="tblDrivers" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ssn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.birth_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.license_degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.companys_id)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ssn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.birth_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.license_degree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.company.name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.id })*@
                    <button class='btn-link js-delete' data-driver-id= @item.id> Delete </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
<script>

    $(document).ready(function () {
        var table = $("#tblDrivers").DataTable();

        $("#tblDrivers").on("click", ".js-delete", function () {
            var button = $(this);
            //bootbox.confirm("Are you sure you want to delete this Car", function (result) {
            //if (result) {
            if (confirm("Are you sure you want to delete this Driver?")){
                    $.ajax({
                        url: '@Url.Action("Delete")'+ "/" + button.attr("data-driver-id"),
                        //type:"DELETE",
                        success: function () {
                            //console.log("Success")
                            table.row(button.parents("tr")).remove().draw();
                        }
                    });
                }

            //});

        });


    });
</script>
}