CTMS - O6U/Controllers/carsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CTMS___O6U.Models;
using System.Net.Http;
using PagedList;
using PagedList.Mvc;

namespace CTMS___O6U.Controllers
{
    public class carsController : Controller
    {
        // GET: cars
        public ActionResult Index(int? id)
        {
            //try
            //{
            //    ViewBag.RequestResult = TempData["RequestResult"].ToString();
            //}
            //catch (Exception) { }
            //List<CarModel> cars = new List<CarModel>();
            //HttpResponseMessage res = ApiCall.getFromApi("api/cars?page");
            //if (res != null)
            //{
            //    cars = res.Content.ReadAsAsync<List<CarModel>>().Result;
            //}
            //return View(cars);

            try
            {
                ViewBag.RequestResult = TempData["RequestResult"].ToString();
            }
            catch (Exception) { }

            List<CarModel> cars = new List<CarModel>();

            if (id == null)
            {
                HttpResponseMessage res = ApiCall.getFromApi("api/cars");

                if (res != null)
                {
                    cars = res.Content.ReadAsAsync<List<CarModel>>().Result;
                    var ret = cars.Where(e => e.Archive == false);
                    return View(ret);
                }
            }
            else
            {
                HttpResponseMessage res = ApiCall.getFromApi("api/cars/" + id);
                if (res != null)
                {
                    cars.Add(res.Content.ReadAsAsync<CarModel>().Result);
                }
            }
            return View(cars);
        }

        [HttpPost]
        public ActionResult Index(string statue)
        {

            TempData["RequestResult"] = statue;
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }
    

        [HttpPost]
        public ActionResult Create([Bind(Include = "id,plate_number,color,Capcity,width,length,weight,satisfied,model,company_id")] CarModel car)
        {
            car.Archive = false;
            int res = ApiCall.getFromApi("api/cars", car);
            switch (res)
            {
                case 201:
                    return Index("Record Added Successfully");
                default:
                    break;
            }
            return Index("Something went worng");
        }

        public ActionResult Edit(int id)
        {
            ViewBag.id = id;
            HttpResponseMessage cardata = ApiCall.getFromApi("api/cars/" + id);
            if (cardata == null)
                return HttpNotFound();

            List<CarModel> cars = new List<CarModel>();
            cars.Add(cardata.Content.ReadAsAsync<CarModel>().Result);
            CarModel car = cars[0];
            return View(car);
        }

        public ActionResult Save(int id, CarModel car)
        {
            int res = ApiCall.getFromApi("api/cars/" + id, car);
            switch (res)
            {
                case 201:
                    return Index("Record Saved Successfully");
                default:
                    break;
            }
            return Index("Something went worng");
        }

        public ActionResult Delete(int id)
        {
            int res = ApiCall.deleteFromApi("api/cars/"+id);
            switch (res)
            {
                case 200:
                    return Index("Record Deleted !");
                default:
                    break;
            }

            return Index("Something went worng");
        }

        public ActionResult Details(int id)
        {
            HttpResponseMessage res = ApiCall.getFromApi("api/cars/" + id);
            CarModel car = new CarModel();
            if (res != null)
            {
                car = res.Content.ReadAsAsync<CarModel>().Result;
            }

            return View(car);
        }

    }
}

CTMS - O6U/Views/cars/Create.cshtml
@model CTMS___O6U.Models.CarModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>CarModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.plate_number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.plate_number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.plate_number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Capcity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Capcity, new { htmlAttributes = new { @class = "form-control", @min = "1" } })
            @Html.ValidationMessageFor(model => model.Capcity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.width, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.width, new { htmlAttributes = new { @class = "form-control", @min = "1" } })
            @Html.ValidationMessageFor(model => model.width, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.length, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.length, new { htmlAttributes = new { @class = "form-control", @min = "1" } })
            @Html.ValidationMessageFor(model => model.length, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.weight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.weight, new { htmlAttributes = new { @class = "form-control", @min = "1" } })
            @Html.ValidationMessageFor(model => model.weight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.satisfied, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.satisfied)
                @Html.ValidationMessageFor(model => model.satisfied, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.model, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.model, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.model, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.company_id, "Comapny Name", htmlAttributes: new { @class = "control-label col-md-2" })
        @*@Html.LabelFor(model => model.company_id, "company_id", htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
            @Html.DropDownList("company_id",
               new SelectList(Enumerable.Empty<SelectListItem>(), "id", "name"),
               "-- Select a Company --",
               new { @class = "form-control" })

            @*@Html.EditorFor(model => model.company_id, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.company_id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   <script>
        $(document).ready(function () {
            $.ajax({
                url: WebApiURL.Url() + "companies",
                contentType: "application/json; charset=utf-8",
                type: "GET",
                data:"",
                dataType:"JSON",
                success: function (result) {
                    $.each(result, function (key, value) {
                        if (value.archive == false)
                            $("#company_id").append($("<option> </option>").val(value.id).html(value.id + ' '  + value.name));
                    });
                },
                error: function (data) { }
            });
        });
    </script>
}

CTMS - O6U/Views/cars/Details.cshtml
@model CTMS___O6U.Models.CarModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CarModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.plate_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.plate_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capcity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capcity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.length)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.length)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.satisfied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.satisfied)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.company_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CTMS - O6U/Views/cars/Edit.cshtml
@model CTMS___O6U.Models.CarModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Save", "Cars"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CarModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.plate_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.plate_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.plate_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capcity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capcity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capcity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.length, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.length, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.length, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.satisfied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.satisfied)
                    @Html.ValidationMessageFor(model => model.satisfied, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.company_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.ValidationMessageFor(model => model.company_id, "", new { @class = "text-danger" })*@
                @Html.DropDownList("company_id",
                        new SelectList(Enumerable.Empty<SelectListItem>(), "id", "name"),
                        "-- Select a Company --",
                        new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.company_id, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(m => m.id)
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
    $(document).ready(function () {
        $.ajax({
            url: WebApiURL.Url()  + "companies",
            contentType: "application/json; charset=utf-8",
            type: "GET",
            data:"",
            dataType:"JSON",
            success: function (result) {
                $.each(result, function (key, value) {
                    if (value.archive == false)
                        $("#company_id").append($("<option> </option>").val(value.id).html(value.id + ' ' + value.name));
                });
                $("#company_id").val(@Model.company_id)
            },
            error: function (data) { }
        });
    });
    </script>


}

CTMS - O6U/Views/cars/Index.cshtml
@model IEnumerable<CTMS___O6U.Models.CarModel>

@{
    ViewBag.Title = "Index";
}

@if (ViewBag.RequestResult != null)
{
    <div class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
        <span class="sr-only">Info:</span>
        @ViewBag.RequestResult
    </div>
}


<h2>Cars Data</h2>

<p>
    @Html.ActionLink("Create New", "Create","cars",null, new {@class="btn btn-primary" })
</p>
<table id="tblCars" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.plate_number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capcity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.satisfied)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.model)
            </th>
            <th>
                @*@Html.DisplayNameFor(model => model.company.name)*@
                @Html.DisplayNameFor(model => model.company_id)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
             
           var warn = !item.satisfied ? "red" : null; 
        <tr bgcolor="@warn">
            <td>
                @Html.DisplayFor(modelItem => item.plate_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capcity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.length)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.weight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.satisfied)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.model)
            </td>
            <td>
                @Html.ActionLink(item.company.name, "Cars", "companies", new { id = item.company_id }, null)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @*@Html.ActionLink("Delete", "Delete", new { id = item.id })*@
                <button class='btn-link js-delete' data-car-id=@item.id> Delete </button>
            </td>
        </tr>
        }
    </tbody>
</table>

@section scripts{
    <script>

    $(document).ready(function () {
        $("#tblCars").DataTable();


        $("#tblCars").on("click", ".js-delete", function () {
            var button = $(this);
            if (confirm("Are you sure you?")){
                    $.ajax({
                        url: '@Url.Action("Delete")' + "/" + button.attr("data-car-id"),
                        //type:"DELETE",
                        success: function () {
                            //console.log("Success")
                            table.row(button.parents("tr")).remove().draw();
                        }
                    });
                }
        });

    });
    </script>
} 